import { Theme } from "@/Theme";

export const skillCategories = [
  {
    category: "Frontend Engineering",
    color: Theme.colors.yellow[400],
    elements: [
      { symbol: "Ts", name: "TypeScript" },
      { symbol: "Wpc", name: "Webpack" },
      { symbol: "Nx", name: "Next.js" },
      { symbol: "Re", name: "React.js" },
      { symbol: "Vt", name: "Vite" },
      { symbol: "Rdx", name: "Redux Toolkit" },
      { symbol: "Zus", name: "Zustand" },
      { symbol: "Rq", name: "React Query" },
      { symbol: "Tw", name: "Tailwind CSS" },
      { symbol: "Shd", name: "Shadcn/ui" },
      { symbol: "Frm", name: "Framer Motion" },
    ],
  },
  {
    category: "Backend & Data",
    color: Theme.colors.blue[400],
    elements: [
      { symbol: "Gql", name: "GraphQL" },
      { symbol: "No", name: "NodeJS" },
      { symbol: "Py", name: "Python" },
      { symbol: "Mon", name: "MongoDB" },
      { symbol: "Exp", name: "ExpressJS" },
      { symbol: "Str", name: "Strapi" },
      { symbol: "Fst", name: "FastAPI" },
      { symbol: "Sql", name: "SQL" },
      { symbol: "Red", name: "Redis" },
      { symbol: "El", name: "Elastic" },
      { symbol: "Cpp", name: "C++" },
      { symbol: "Rb", name: "RabbitMQ" },
      { symbol: "Ws", name: "WebSockets" },
    ],
  },
   {
    category: "Product & Strategy",
    color: Theme.colors.orange[400],
    elements: [
      { symbol: "Abt", name: "A/B Testing" },
      { symbol: "Agl", name: "Agile Methodologies" },
      { symbol: "Mkt", name: "Market Analysis" },
      { symbol: "Wfr", name: "Wireframing" },
      { symbol: "Rdm", name: "Roadmap Planning" },
      { symbol: "Okr", name: "OKR Setting" },
      { symbol: "Prd", name: "PRD/PRFAQ Docs" },
      { symbol: "Scr", name: "Scrum" },
      { symbol: "Bkl", name: "Backlog Management" },
      { symbol: "Spr", name: "Sprint Planning" },
      { symbol: "Stk", name: "Stakeholder Comms" },
      { symbol: "Rsk", name: "Risk Management" },
    ],
  },
  {
    category: "Analytics & SEO",
    color: Theme.colors.green[400],
    elements: [
      { symbol: "Pos", name: "Posthog" },
      { symbol: "Kib", name: "Kibana" },
      { symbol: "Gan", name: "Google Analytics" },
      { symbol: "Cla", name: "MS Clarity" },
      { symbol: "Lth", name: "Lighthouse" },
      { symbol: "Gsc", name: "Google Search Console" },
      { symbol: "Gtm", name: "Google Tag Manager" },
    ],
  },
  {
    category: "DevOps & Cloud",
    color: Theme.colors.pink[400],
    elements: [
      { symbol: "Ec2", name: "EC2" },
      { symbol: "S3", name: "S3" },
      { symbol: "Jen", name: "Jenkins" },
      { symbol: "Dkr", name: "Docker" },
      { symbol: "K8s", name: "Kubernetes" },
      { symbol: "R53", name: "Route53" },
      { symbol: "Cw", name: "CloudWatch" },
      { symbol: "Lam", name: "Lambda" },
      { symbol: "Cf", name: "CloudFront" },
      { symbol: "Sns", name: "Simple Notification Service" },
      { symbol: "Sqs", name: "Simple Queue Service" },
      { symbol: "Ebs", name: "Elastic Block Store" },
      { symbol: "Efs", name: "Elastic File System" },
      { symbol: "Rds", name: "Relational Database Service" },
    ],
  },
  {
    category: "AI Tools",
    color: Theme.colors.purple[400],
    elements: [
      { symbol: "Pt", name: "PyTorch" },
      { symbol: "Gpt", name: "ChatGPT" },
      { symbol: "Cld", name: "Claude" },
      { symbol: "Gem", name: "Gemini" },
      { symbol: "Cdx", name: "Codex" },
      { symbol: "Crb", name: "CodeRabbit" },
      { symbol: "Jai", name: "JulesAI" },
      { symbol: "Tae", name: "Trae" },
      { symbol: "Cur", name: "Cursor" },
      { symbol: "N8n", name: "n8n" },
      { symbol: "Sti", name: "Google Stitch" },
      { symbol: "Cau", name: "CausalML" },
    ],
  },
  {
    category: "Specialized Tools",
    color: Theme.colors.red[400],
    elements: [
      { symbol: "Mwz", name: "Mailwizz" },
      { symbol: "Of", name: "OpenFold" },
      { symbol: "Chi", name: "ChimeraX" },
      { symbol: "Bri", name: "Brian2" },
      { symbol: "Col", name: "Colab" },
      { symbol: "Wba", name: "Bundle Analyzer" },
      { symbol: "Atl", name: "Atlassian" },
      { symbol: "Git", name: "Github" },
      { symbol: "Can", name: "Canva" },
    ],
  },
];
